-- Migration 022: Paper-only OI/ML shadow order lifecycle.
--
-- This table records dry-run order intents generated by the intraday OI/ML
-- CE-seller. These rows are audit/shadow lifecycle records only. They are not
-- broker orders, and the dry_run_only check prevents accidental reuse as a
-- live order queue.

CREATE TABLE IF NOT EXISTS public.oi_ml_shadow_order_intents (
    id                           BIGSERIAL PRIMARY KEY,
    intent_id                    TEXT        NOT NULL UNIQUE,
    strategy_id                  TEXT        NOT NULL,
    tenant_id                    TEXT,
    broker_account_id            TEXT,
    status                       TEXT        NOT NULL
        CHECK (status IN ('STAGED', 'REJECTED', 'EXPIRED', 'CANCELLED')),
    structure                    TEXT        NOT NULL,
    underlying                   TEXT        NOT NULL,
    expiry                       DATE        NOT NULL,
    short_strike                 INTEGER     NOT NULL,
    quantity                     INTEGER     NOT NULL CHECK (quantity > 0),
    estimated_net_credit_points  NUMERIC(14, 6) NOT NULL,
    estimated_max_loss_rupees    NUMERIC(14, 2)  NOT NULL,
    dry_run_only                 BOOLEAN     NOT NULL DEFAULT TRUE CHECK (dry_run_only = TRUE),
    decision_reason              TEXT,
    guard_reasons                JSONB       NOT NULL DEFAULT '[]'::jsonb,
    intent_payload               JSONB       NOT NULL,
    created_at                   TIMESTAMPTZ NOT NULL,
    recorded_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_oi_ml_shadow_intents_created_at
    ON public.oi_ml_shadow_order_intents (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_oi_ml_shadow_intents_strategy_time
    ON public.oi_ml_shadow_order_intents (strategy_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_oi_ml_shadow_intents_account_time
    ON public.oi_ml_shadow_order_intents (tenant_id, broker_account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_oi_ml_shadow_intents_payload
    ON public.oi_ml_shadow_order_intents USING GIN (intent_payload);

COMMENT ON TABLE public.oi_ml_shadow_order_intents IS
    'Paper-only dry-run OI/ML order intents. This is an audit table, not an order queue.';

COMMENT ON COLUMN public.oi_ml_shadow_order_intents.dry_run_only IS
    'Invariant marker. Must remain TRUE; rows from this table must not be submitted to a broker.';
